/// DEFAULT_SEARXNG_BASE_URL 表示默认 SearxNG 搜索地址。
pub const DEFAULT_SEARXNG_BASE_URL: &str = "https://searxng.website/searxng/search";

/// DEFAULT_SEARXNG_FALLBACK_BASE_URL 表示默认 SearxNG 回退搜索地址。
pub const DEFAULT_SEARXNG_FALLBACK_BASE_URL: &str = "https://search.liuzj.net/search";

/// DEFAULT_SEARXNG_PRESELECT_LIMIT 表示搜索前参与快速预选的镜像数量。
pub(super) const DEFAULT_SEARXNG_PRESELECT_LIMIT: usize = 12;

/// DEFAULT_SEARXNG_PRESELECT_GOAL 表示搜索前最多预选出的可用镜像数量。
pub(super) const DEFAULT_SEARXNG_PRESELECT_GOAL: usize = 3;

/// DEFAULT_SEARXNG_MIRRORS 表示内置 SearxNG 镜像搜索地址列表。
pub const DEFAULT_SEARXNG_MIRRORS: &[&str] = &[
    DEFAULT_SEARXNG_BASE_URL,
    "https://priv.au/",
    "https://searx.ononoki.org/",
    "https://failsearx.culturanerd.it/",
    "https://searxng.shreven.org/",
    "https://searxng.gdebest.net/",
    "https://search.einfachzocken.eu/",
    "https://searxng.fishfvch.com/",
    "https://search.undertale.uk/",
    "https://searx.rhscz.eu/",
    "https://searx.oloke.xyz/",
    "https://xka.cz/",
    "https://searxng.canine.tools/",
    "https://search.pi.vps.pw/",
    "https://baresearch.org/",
    "https://searxng.wuemeli.com/",
    "https://search.rhscz.eu/",
    "https://search.bladerunn.in/",
    "https://search.mdosch.de/",
    "https://searx.namejeff.xyz/",
    "https://searx.tsmdt.de/",
    "https://search.ctq.ro/",
    "https://search.femboy.ad/",
    DEFAULT_SEARXNG_FALLBACK_BASE_URL,
    "https://opnxng.com/",
    "https://search.minus27315.dev/",
    "https://search.seddens.net/",
    "https://grep.vim.wtf/",
    "https://search.wdpserver.com/",
    "https://search.chocolatemoo53.com/",
    "https://www.gruble.de/",
    "https://searx.ro/",
    "https://searxng.cups.moe/",
    "https://searxng.gr/",
    "https://search.privacyredirect.com/",
    "https://etsi.me/",
    "https://ooglester.com/",
    "https://search.abohiccups.com/",
    "https://copp.gg/",
    "https://searx.tiekoetter.com/",
    "https://search.sapti.me/",
    "https://paulgo.io/",
    "https://searxng.deggo.fyi/",
    "https://searx.rajimayur.me/",
    "https://search.inetol.net/",
    "https://searxng.site/",
    "https://searx.mbuf.net/",
    "https://find.xenorio.xyz/",
    "https://kantan.cat/",
    "https://search.2b9t.xyz/",
    "https://search.anoni.net/",
    "https://search.catboy.house/",
    "https://search.ethibox.fr/",
    "https://search.hbubli.cc/",
    "https://search.im-in.space/",
    "https://search.indst.eu/",
    "https://search.pereira.is/",
    "https://search.rowie.at/",
    "https://search.serpensin.com/",
    "https://search.url4irl.com/",
    "https://search.zina.dev/",
    "https://searx.ankha.ac/",
    "https://searx.linxx.net/",
    "https://searx.party/",
    "https://searx.perennialte.ch/",
    "https://searx.redgarden.cv/",
    "https://searx.tuxcloud.net/",
    "https://searx.sev.monster/",
    "https://search.unredacted.org/",
    "https://search.root.hr/",
    "https://searx.mxchange.org/",
    "https://searx.dresden.network/",
];
